import type { Deal, Activity, Contact } from './types'

export const deals: Deal[] = [
  {
    id: 'd1',
    company: 'TechFlow BV',
    contact: 'Sanne de Vries',
    email: '',
    phone: '',
    value: 84000,
    stage: 'onderhandeling',
    probability: 75,
    sqm: 350,
    location: 'Amsterdam Zuidas',
    createdAt: '2026-02-10',
    expectedClose: '2026-05-01',
    lastActivity: '2026-04-20',
    notes: 'Interesse in flexibele contractvorm. CEO betrokken bij beslissing.',
  },
  {
    id: 'd2',
    company: 'Studio Rooftop',
    contact: 'Lars Hendriks',
    email: '',
    phone: '',
    value: 36000,
    stage: 'voorstel',
    probability: 55,
    sqm: 150,
    location: 'Amsterdam Oost',
    createdAt: '2026-03-01',
    expectedClose: '2026-05-15',
    lastActivity: '2026-04-18',
    notes: 'Offerte verstuurd. Wacht op feedback na intern overleg.',
  },
  {
    id: 'd3',
    company: 'Healthify Labs',
    contact: 'Priya Nair',
    email: '',
    phone: '',
    value: 120000,
    stage: 'gekwalificeerd',
    probability: 40,
    sqm: 500,
    location: 'Amsterdam Centrum',
    createdAt: '2026-03-15',
    expectedClose: '2026-06-30',
    lastActivity: '2026-04-22',
    notes: 'Snelgroeiend bedrijf, 2e kantoor nodig. Budget nog te bevestigen.',
  },
  {
    id: 'd4',
    company: 'Nomadic Digital',
    contact: 'Bo Vermeer',
    email: '',
    phone: '',
    value: 18000,
    stage: 'gewonnen',
    probability: 100,
    sqm: 75,
    location: 'Amsterdam Oost',
    createdAt: '2026-01-20',
    expectedClose: '2026-04-01',
    lastActivity: '2026-04-01',
    notes: 'Contract getekend. Incheck 1 mei.',
  },
  {
    id: 'd5',
    company: 'Klarion Advocaten',
    contact: 'Marc Jansen',
    email: '',
    phone: '',
    value: 96000,
    stage: 'lead',
    probability: 20,
    sqm: 400,
    location: 'Amsterdam Zuidas',
    createdAt: '2026-04-10',
    expectedClose: '2026-07-30',
    lastActivity: '2026-04-10',
    notes: 'Binnengehaald via LinkedIn. Eerste afspraak ingepland.',
  },
  {
    id: 'd6',
    company: 'Groen & Partners',
    contact: 'Femke Groen',
    email: '',
    phone: '',
    value: 48000,
    stage: 'verloren',
    probability: 0,
    sqm: 200,
    location: 'Amsterdam Centrum',
    createdAt: '2026-02-01',
    expectedClose: '2026-04-15',
    lastActivity: '2026-04-15',
    notes: 'Gekozen voor concurrent. Prijs was doorslaggevend.',
  },
  {
    id: 'd7',
    company: 'Bloom Creative',
    contact: 'Julia Bakker',
    email: '',
    phone: '',
    value: 28800,
    stage: 'voorstel',
    probability: 60,
    sqm: 120,
    location: 'Amsterdam Oost',
    createdAt: '2026-03-22',
    expectedClose: '2026-05-30',
    lastActivity: '2026-04-21',
    notes: 'Positieve reactie op tour. Offerte aanpassen naar 2 jaar.',
  },
  {
    id: 'd8',
    company: 'DataSphere',
    contact: 'Koen Mulder',
    email: '',
    phone: '',
    value: 72000,
    stage: 'gekwalificeerd',
    probability: 45,
    sqm: 300,
    location: 'Amsterdam Zuidas',
    createdAt: '2026-04-05',
    expectedClose: '2026-07-01',
    lastActivity: '2026-04-19',
    notes: 'Behoefte aan server/datacenterruimte. Specifieke eisen qua koeling.',
  },
]

export const activities: Activity[] = [
  {
    id: 'a1',
    type: 'meeting',
    dealId: 'd1',
    company: 'TechFlow BV',
    contact: 'Sanne de Vries',
    description: 'Contractbespreking met CEO en CFO',
    date: '2026-04-24',
    done: false,
  },
  {
    id: 'a2',
    type: 'call',
    dealId: 'd2',
    company: 'Studio Rooftop',
    contact: 'Lars Hendriks',
    description: 'Follow-up offerte, feedback ophalen',
    date: '2026-04-23',
    done: false,
  },
  {
    id: 'a3',
    type: 'tour',
    dealId: 'd3',
    company: 'Healthify Labs',
    contact: 'Priya Nair',
    description: 'Rondleiding Amsterdam Centrum locatie',
    date: '2026-04-25',
    done: false,
  },
  {
    id: 'a4',
    type: 'email',
    dealId: 'd5',
    company: 'Klarion Advocaten',
    contact: 'Marc Jansen',
    description: 'Bevestiging kennismakingsgesprek sturen',
    date: '2026-04-23',
    done: true,
  },
  {
    id: 'a5',
    type: 'meeting',
    dealId: 'd7',
    company: 'Bloom Creative',
    contact: 'Julia Bakker',
    description: 'Aangepaste offerte presenteren',
    date: '2026-04-28',
    done: false,
  },
  {
    id: 'a6',
    type: 'call',
    dealId: 'd8',
    company: 'DataSphere',
    contact: 'Koen Mulder',
    description: 'Technische vereisten bespreken met facilitair manager',
    date: '2026-04-26',
    done: false,
  },
  {
    id: 'a7',
    type: 'note',
    dealId: 'd4',
    company: 'Nomadic Digital',
    contact: 'Bo Vermeer',
    description: 'Welkomstpakket klaargemaakt voor incheck 1 mei',
    date: '2026-04-22',
    done: true,
  },
]

export const contacts: Contact[] = [
  {
    id: 'c1',
    name: 'Sanne de Vries',
    company: 'TechFlow BV',
    email: 'sanne@techflow.nl',
    phone: '+31 6 12345678',
    role: 'COO',
    source: 'referral',
    status: 'actief',
    createdAt: '2026-02-10',
  },
  {
    id: 'c2',
    name: 'Lars Hendriks',
    company: 'Studio Rooftop',
    email: 'lars@studiorooftop.nl',
    phone: '+31 6 23456789',
    role: 'Founder',
    source: 'website',
    status: 'actief',
    createdAt: '2026-03-01',
  },
  {
    id: 'c3',
    name: 'Priya Nair',
    company: 'Healthify Labs',
    email: 'p.nair@healthify.io',
    phone: '+31 6 34567890',
    role: 'CEO',
    source: 'linkedin',
    status: 'actief',
    createdAt: '2026-03-15',
  },
  {
    id: 'c4',
    name: 'Bo Vermeer',
    company: 'Nomadic Digital',
    email: 'bo@nomadic.digital',
    phone: '+31 6 45678901',
    role: 'Managing Director',
    source: 'event',
    status: 'actief',
    createdAt: '2026-01-20',
  },
  {
    id: 'c5',
    name: 'Marc Jansen',
    company: 'Klarion Advocaten',
    email: 'm.jansen@klarion.nl',
    phone: '+31 6 56789012',
    role: 'Partner',
    source: 'linkedin',
    status: 'prospect',
    createdAt: '2026-04-10',
  },
  {
    id: 'c6',
    name: 'Femke Groen',
    company: 'Groen & Partners',
    email: 'femke@groenpartners.nl',
    phone: '+31 6 67890123',
    role: 'Directeur',
    source: 'cold',
    status: 'inactief',
    createdAt: '2026-02-01',
  },
  {
    id: 'c7',
    name: 'Julia Bakker',
    company: 'Bloom Creative',
    email: 'julia@bloomcreative.nl',
    phone: '+31 6 78901234',
    role: 'Creative Director',
    source: 'referral',
    status: 'actief',
    createdAt: '2026-03-22',
  },
  {
    id: 'c8',
    name: 'Koen Mulder',
    company: 'DataSphere',
    email: 'k.mulder@datasphere.nl',
    phone: '+31 6 89012345',
    role: 'CTO',
    source: 'website',
    status: 'actief',
    createdAt: '2026-04-05',
  },
]
